### PR TITLE
Add a rendered list of the full stack to PR descriptions

### LINKED ISSUE #139: Visualize the stack in the PR description
[ghstack](https://github.com/ezyang/ghstack) has a nice feature visualizing the stack:

image

Large stacks are usually reviewed in order, so this would be a useful feature to have (or perhaps it already does and I just didn't know how to turn it on?)

### PR DESCRIPTION
**Pull request by leoluk**
Requires a change to the main update logic: we now need to
always update every PR, since we need to update the messages
of lower PRs when an upper PR is changed.

Also, when creating new PRs, the list of stacked PRs would
be incomplete. Queue all mutations and execute them at the
end to fix this.

Fixes #139

commit-id:28b937ff

### CODE REVIEW

**Review by ejoffe — COMMENTED** [review]
This is super awesome! All the code changes look good to me. 
Since we now update all the pull requests in the stack every time. Does it mean that github actions will rerun for all the pull requests in the stack on every update?

**Comment by leoluk** [comment]
> Does it mean that github actions will rerun for all the pull requests in the stack on every update?

Only if the commit changes, I think - updating the description won't trigger it

**Review by ejoffe — APPROVED** [review]

**Comment by ejoffe** [comment]
I can take a stab at updating the unit test. That is test is a bit tricky to debug with setting the mock expectations correctly.

**Comment by leoluk** [comment]
Would be much appreciated

**Comment by ejoffe** [comment]
Done. #142

**Pull request closed without merging**
