### PR TITLE
GITHUB-407: Gracefully handle Cygwin paths on Windows when determining root directory

### LINKED ISSUE #407: Fails on windows under cygwin when determining git's root directory
On windows, when run in Cygwin environment, it fails like below:

```
git spr

git error: 
chdir /cygdrive/c/dev/sourceCode/temp-playground/spr: The system cannot find the path specified.

Process finished with the exit code 2
```

Apparently, `git rev-parse ...` command returns cygwin-based path because it uses Cygwin version of git. It would be optimal if the tool could take that into account.

### PR DESCRIPTION
**Pull request by anenviousguest**
Fixes #407

### CODE REVIEW

**Comment by anenviousguest** [comment]
hi @ejoffe , any chance to get the feedback on this ? thanks.

**Review by ejoffe — APPROVED** [review]

**Comment by ejoffe** [comment]
Sorry about the delay. Looks good to me. 
One nit: is there a better check to see if it's cygwin instead of checking the HasPrefix equal to cygdrive? this seems fragile.

**Comment by anenviousguest** [comment]
Hi @ejoffe 

> is there a better check to see if it's cygwin instead of checking the HasPrefix equal to cygdrive? this seems fragile.

within shell scripts, the check would typically be based on `uname -a` command output - but apparently this won't work if `spr` is running in plain CMD environment. So i didn't want to overcomplicate the implementations which i won't be able to test anyway, because my cygwin paths all start with `/cygdrive`

**Comment by anenviousguest** [comment]
@ejoffe any chance to get this merged ? 😅

**Pull request merged**
